name: build-linux-client

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: client (${{ matrix.target }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-unknown-linux-musl, aarch64-unknown-linux-musl ]

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) and targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.12.0

      - name: Cache cargo registry + git + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild --locked

      - name: Compute version
        shell: bash
        run: |
          set -euxo pipefail
          ver=$(git describe --tags --always --dirty || echo "dev")
          echo "VERSION=$ver" >> "$GITHUB_ENV"

      - name: Build client (musl, static)
        run: |
          cargo zigbuild --release --target ${{ matrix.target }} --bin dnsm-client

      - name: Package artifacts
        shell: bash
        run: |
          set -euxo pipefail
          outdir="dist/${{ matrix.target }}"
          mkdir -p "$outdir"
          cp "target/${{ matrix.target }}/release/dnsm-client" "$outdir/"
          strip -s "$outdir/dnsm-client" || true
          tar czf "dnsm-client-${{ env.VERSION }}-${{ matrix.target }}.tar.gz" -C "$outdir" dnsm-client
          sha256sum "dnsm-client-${{ env.VERSION }}-${{ matrix.target }}.tar.gz" > "dnsm-client-${{ env.VERSION }}-${{ matrix.target }}.tar.gz.sha256"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dnsm-client-${{ matrix.target }}
          path: |
            dnsm-client-${{ env.VERSION }}-${{ matrix.target }}.tar.gz
            dnsm-client-${{ env.VERSION }}-${{ matrix.target }}.tar.gz.sha256
