name: release-github

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.0" # run only on minor releases (patch == 0)
  workflow_dispatch:
    inputs:
      version:
        description: "SemVer to build (e.g., 1.2.3). Leave empty to use Cargo.toml"
        required: false
        type: string
      create_release:
        description: "Also create a GitHub Release (manual runs)"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    name: build (${{ matrix.bin }} @ ${{ matrix.target }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
        bin: [dnsm-client, dnsm-server, dnsm-ws]

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) and targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.12.0

      - name: Cache cargo registry + git + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild --locked

      - name: Compute version (tag or input)
        shell: bash
        run: |
          set -euxo pipefail
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ver="${{ inputs.version }}"
            if [ -z "$ver" ]; then
              ver=$(sed -n 's/^version\s*=\s*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)"/\1/p' Cargo.toml | head -n1)
            fi
            tag="v${ver}"
          else
            tag="${GITHUB_REF_NAME}"
            ver="${tag#v}"
          fi
          echo "TAG=$tag" >> "$GITHUB_ENV"
          echo "VERSION=$ver" >> "$GITHUB_ENV"

      - name: Verify Cargo.toml version matches tag/version
        shell: bash
        run: |
          set -euxo pipefail
          cargo_version=$(sed -n 's/^version\s*=\s*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)"/\1/p' Cargo.toml | head -n1)
          if [ -z "$cargo_version" ]; then
            echo "Failed to parse version from Cargo.toml" >&2
            exit 1
          fi
          if [ "$cargo_version" != "$VERSION" ]; then
            echo "Tag ($VERSION) does not match Cargo.toml version ($cargo_version)" >&2
            exit 1
          fi

      - name: Build ${{ matrix.bin }} (musl, static)
        shell: bash
        env:
          BIN: ${{ matrix.bin }}
        run: |
          set -euxo pipefail
          case "$BIN" in
            dnsm-client) FEATURES="" ;;
            dnsm-server) FEATURES="sqlite" ;;
            dnsm-ws)     FEATURES="sqlite,ws-server" ;;
            *) echo "Unknown bin: $BIN" >&2; exit 1 ;;
          esac
          if [ -n "$FEATURES" ]; then
            cargo zigbuild --release --target ${{ matrix.target }} --bin "$BIN" --features "$FEATURES"
          else
            cargo zigbuild --release --target ${{ matrix.target }} --bin "$BIN"
          fi

      - name: Package artifacts
        shell: bash
        run: |
          set -euxo pipefail
          outdir="dist/${{ matrix.target }}"
          mkdir -p "$outdir"
          cp "target/${{ matrix.target }}/release/${{ matrix.bin }}" "$outdir/"
          strip -s "$outdir/${{ matrix.bin }}" || true
          tar_name="${{ matrix.bin }}-${VERSION}-${{ matrix.target }}.tar.gz"
          tar czf "$tar_name" -C "$outdir" "${{ matrix.bin }}"
          sha256sum "$tar_name" > "$tar_name.sha256"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bin }}-${{ matrix.target }}
          path: |
            ${{ matrix.bin }}-${{ env.VERSION }}-${{ matrix.target }}.tar.gz
            ${{ matrix.bin }}-${{ env.VERSION }}-${{ matrix.target }}.tar.gz.sha256

  release:
    name: publish release
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.create_release)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute version (tag or input)
        shell: bash
        run: |
          set -euxo pipefail
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ver="${{ inputs.version }}"
            if [ -z "$ver" ]; then
              ver=$(sed -n 's/^version\s*=\s*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)"/\1/p' Cargo.toml | head -n1)
            fi
            tag="v${ver}"
          else
            tag="${GITHUB_REF_NAME}"
            ver="${tag#v}"
          fi
          echo "TAG=$tag" >> "$GITHUB_ENV"
          echo "VERSION=$ver" >> "$GITHUB_ENV"
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: dnsm ${{ env.TAG }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/*.tar.gz
            artifacts/*.sha256
